openapi: 3.1.0
x-stoplight:
  id: bp609kelx8xh5
info:
  title: bfile1-3.1
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    id: lh0cbk7ux48lb
    patch:
      x-stoplight:
        id: rskmwmu2x4xb0
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: cl6l5exr1mr34
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: sykb22pykhxns
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: 0tv3mrkdg4nd6
        firstName:
          type: string
          x-stoplight:
            id: 4rkglds7n62w6
        lastName:
          type: string
          x-stoplight:
            id: utn0xttuk2qa4
        email:
          type: string
          format: email
          x-stoplight:
            id: bjxr3ujn8h2oa
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: gy1sah9m4x8iy
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: u7eb5k3k66ym6
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: qyafzom30q94h
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
