openapi: 3.1.0
x-stoplight:
  id: n0qmwflmbzovq
info:
  title: test1
  version: '1.0'
  description: test1
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    id: o4fwb1gteg438
    patch:
      x-stoplight:
        id: m8mejxdarf47d
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: 1cxgqx98r0lck
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: nlp01pdvtxgh8
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: khmppkpiri9bg
        firstName:
          type: string
          x-stoplight:
            id: h49ib47gi384a
        lastName:
          type: string
          x-stoplight:
            id: 75elsk3ztdli1
        email:
          type: string
          format: email
          x-stoplight:
            id: veb1ohiegcezx
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: joc9uvteuij5k
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: q8im0me9su2qj
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 8ehul4e00motl
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
