openapi: 3.1.0
x-stoplight:
  id: 1rcl6ihtc3f4m
info:
  title: test-3.1
  version: '1.0'
  description: test1
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    id: 7ekzepvcait3a
    patch:
      x-stoplight:
        id: 97wbon1em6nph
  /user:
    id: 80nm1qvmt2q6q
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: 7dk43fozxuy4s
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: f3tp0ygr2r85y
        firstName:
          type: string
          x-stoplight:
            id: u2ucl9v792wjv
        lastName:
          type: string
          x-stoplight:
            id: x51cvj2u54wdr
        email:
          type: string
          format: email
          x-stoplight:
            id: bun2nn696v3yt
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: 5mc03nwyfrxjk
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: hcz7yq7x0tys3
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 3dzwbuyr5l7a4
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
